setting up theme for light and dark mode
khankhail-llc/IslamEncylo pull request #10
Opened 2023-04-17 06:22 UTC by muhammadhassan2k3

implementaion for  [that](https://trello.com/c/GVyy89BQ)

A branch from hassan that includes
* light and dark theme

2023-04-17 08:06 UTC, KamranKhankhail commented on src/screens/HomeScreen.tsx
> +        <StatusBar barStyle={theme === 'dark' ? 'light-content' : 'dark-content'} />
@muhammadhassan2k3 will we use these conditionals through out the application ?

2023-04-17 08:18 UTC, KamranKhankhail commented on src/screens/HomeScreen.tsx
> +        <StatusBar barStyle={theme === 'dark' ? 'light-content' : 'dark-content'} />
@muhammadhassan2k3 we should first standardise all the colors names in the app. for example, for all the headings in the Header of the screens, we can name it `screenTitle` and then define it something like following:

```typescript

export const THEME_COLORS = {
   light: {
     screenTitle: "#fff",
     leftHeaderIcon: "#fff",
   },
   dark: {
     screenTitle: "#000"
   }
}

```

then we can write a utility function like following to get the color based upon theme & color name

```typescript
export const getColorByName (theme: Theme, colorName: ColorNames) {
   return THEME_COLORS?.[theme]?.[colorName];
}
```


OR we can create hooks like following:

```
useColors () {
   const theme = useTheme();
   return THEME_COLORS[theme];
}
```

then wherever, we want to use colors we use it like:

```
const colors = useColors()
const screenTitle = colors?.screenTitle;
```

2023-04-17 08:19 UTC, KamranKhankhail commented on src/screens/splashScreen/SplashScreen.tsx
> +import myImage from '../../../assets/launchScreen.png';
@muhammadhassan2k3 can you please use meaningfull name for it instead of `myImage` ?

it could be called as `launchScreen`

2023-04-17 08:20 UTC, KamranKhankhail requested changes
thanks for the changes.

I've added few comments please check & let me know if any discussion is required.

2023-04-17 08:21 UTC, muhammadhassan2k3 commented on src/screens/splashScreen/SplashScreen.tsx
> +import myImage from '../../../assets/launchScreen.png';
sure

2023-04-19 10:58 UTC, KamranKhankhail commented on src/screens/splashScreen/SplashScreen.tsx
> +import myImage from '../../../assets/launchScreen.png';
@muhammadhassan2k3 it is still myImage. Rename it to something meaningful.

2023-06-14 11:16 UTC, KamranKhankhail approved these changes
LGTM. 👍🏼

2023-06-22 06:46 UTC, merged